[tool.poetry]
name = "trading-strategy-getting-started"
version = "0.1"
description = "Trading Strategy Getting Started kit"
authors = ["Mikko Ohtamaa <mikko@opensourcehacker.com>"]
license = "MIT"
readme = "README.md"
keywords = ["algorithmic trading", "ethereum", "cryptocurrency", "tradingview", "quantitative finance", "binance", "coinbase", "uniswap"]
homepage = "https://tradingstrategy.ai"
repository = "https://github.com/tradingstrategy-ai/getting-started"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
trade-executor = {path = "deps/trade-executor", develop = true, extras=["execution", "quantstats"]}
ipython = "^8.12.0"
ipdb = "^0.13.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
