name: Run Jupyter Notebooks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any other version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbformat nbconvert

    - name: Run notebooks
      run: |
        python run_notebooks.py
